### ISSUE TITLE
Beta OR: Error message when trying to add resources under Manager project

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/tc-online-review#155]
Description:

Getting error message when trying to add resources under Manager project. But we are able to add the same resource with same role using the Edit project.

https://user-images.githubusercontent.com/55895538/166203429-98fa0afb-a806-47c7-b454-24de3d379913.mp4

https://user-images.githubusercontent.com/55895538/166203803-b312286c-46cb-46f8-b3c7-2ac444c936ef.mp4

cc: @Gunasekar-K @standlove

**Comment by standlove** [comment]
I see this error in log.  @xxcxy

```
2022-05-02 07:20:03,272 ERROR [onlinereview] java.lang.IllegalArgumentException: org.hibernate.hql.ast.QuerySyntaxException: ContestEligibility is not mapped [from ContestEligibility c where c.contestId=:contestId and c.studio=:studio]
--
java.lang.IllegalArgumentException: org.hibernate.hql.ast.QuerySyntaxException: ContestEligibility is not mapped [from ContestEligibility c where c.contestId=:contestId and c.studio=:studio]
at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:616)
at org.hibernate.ejb.AbstractEntityManagerImpl.createQuery(AbstractEntityManagerImpl.java:95)
at com.topcoder.service.contest.eligibility.dao.ContestEligibilityManagerBean.getContestEligibility(ContestEligibilityManagerBean.java:258)
at com.cronos.onlinereview.ejblibrary.ContestEligibilityManagerLibrary.getContestEligibility(ContestEligibilityManagerLibrary.java:85)

```

**Comment by xxcxy** [comment]
please check the `ContestEligibility.hbm.xml` file in the `WEB-INF/classes` folder

**Comment by standlove** [comment]
This one is fixed.  @sandhiyakavi

**Comment by SathyaJayabal** [comment]
@standlove, still see the issue

https://user-images.githubusercontent.com/58783823/166618421-eb15efdb-4836-48fc-bba1-07cd80ab1ff1.mov

**Comment by SathyaJayabal** [comment]
@standlove , seems the issue is present for some projects. Here is the project that I used which had the error.
https://softwarev1.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30061435

**Comment by standlove** [comment]
Let me check.

**Comment by standlove** [comment]
Please check again.  @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@standlove, issue is fixed, user is able to edit resources from the manage project page

https://user-images.githubusercontent.com/58783823/166663739-bee28eaa-e0c9-4089-8058-0ee85d3b951b.mov

**Comment by codejamtc** [comment]
https://user-images.githubusercontent.com/42398485/168780110-dace0fe9-d9f7-44c1-85cd-edddde88f84a.mp4
